In [3]:
# importing the packages
import numpy as np
import pandas as pd
from ortools.linear_solver import pywraplp
from warnings import filterwarnings

filterwarnings("ignore")

# reading the dataframe
pair_matrix = pd.read_csv("../data/pairings/pair_matrix.csv")
cost_martix = pd.read_csv("../data/cost_matrix/cost_matrix.csv")

# determining the number of flights and tasks
num_pairs = pair_matrix.shape[0]
num_flights = pair_matrix.shape[1]

# Initializing the MIP Solver
solver = pywraplp.Solver.CreateSolver("SCIP")

# creating the binary allocation variable
x = [solver.IntVar(0,1,"") for i in range (num_pairs)]

# declaring the constraints
# Uniqueness of flight legs and all flight legs covered
for i in range(num_flights):
    solver.Add(solver.Sum(pair_matrix.mul(x, axis=0).iloc[:,i]) == 1)

In [18]:
# declaring the objective function
solver.Minimize(solver.Sum(cost_martix['cost'][i] * x[i] for i in range(num_pairs)))

# Solve the problem
status = solver.Solve()

# print the state of the optimization problem
if status == pywraplp.Solver.OPTIMAL:
    print("The Solution is OPTIMAL")
elif status == pywraplp.Solver.FEASIBLE:
    print("The Solution is Feasible")
else:
    print("The Solution is not Feasible")

The Solution is not Feasible


In [19]:
# Displaying the final output binary decision variable
X = [x[i].solution_value() for i in range(num_pairs)]

df = pd.DataFrame(X)

In [20]:
df

,0
0,0.0
1,0.0
2,0.0
3,0.0
4,0.0
...,...
547,0.0
548,0.0
549,0.0
550,0.0


In [31]:
pair_matrix.sum().max()

123

In [32]:
import numpy as np
array = pair_matrix.values
print(array)
print(type(array))

[[0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
<class 'numpy.ndarray'>
